<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.naturalist</groupId>
        <artifactId>domains</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>apiary</artifactId>
    <packaging>pom</packaging>
    <name>domains :: apiary</name>

    <modules>
        <module>apiary-api</module>
        <module>apiary-core</module>
        <module>apiary-repository-test</module>
    </modules>

</project>
