<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.naturalist</groupId>
        <artifactId>domains</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>insects</artifactId>
    <packaging>pom</packaging>
    <name>domains :: insects</name>

    <modules>
        <module>insects-api</module>
        <module>insects-console</module>
        <module>insects-core</module>
        <module>insects-repository-test</module>
        <module>insects-repository-rdms</module>
        <module>insects-test-context</module>
    </modules>

</project>
